### ISSUE TITLE
Explore page table column priority for narrow screens

### ISSUE THREAD

**Issue by PeteTomlin** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#16]
Can fields be set with a priority order for narrow screens? i.e. Vice county, SRC & ID not as important to see as common name and location. 

![image](https://user-images.githubusercontent.com/75690789/101611943-0600e680-3a02-11eb-8ab3-a14cbdbf6320.png)

**Comment by simonrolph** [comment]
You can click the spanner in the top right and use the checkboxes to show/hide any columns you do/don't want to see

**Comment by PeteTomlin** [comment]
Would be better if that was automated to set some columns as priority.

**Comment by johnvanbreda** [comment]
Datagrid documentation at https://indicia-docs.readthedocs.io/en/latest/site-building/iform/helpers/elasticsearch-report-helper.html#elasticsearchreporthelper-datagrid - in particular see the columns option and the documentation of breakpoints within it.

**Comment by simonrolph** [comment]
Thanks @johnvanbreda there I was assuming it wasn't possible! I'll see what I can do @PeteTomlin

**Comment by simonrolph** [comment]
Issue fixed by changing lines in the explore page Form structure:
`{"caption":"Common name","field":"taxon.vernacular_name","hide-breakpoints":"xs,sm,md"},` to
`{"caption":"Common name","field":"taxon.vernacular_name","hide-breakpoints":"xs"},`

and

`{"caption":"Vice county","field":"#higher_geography:Vice County:name#","hide-breakpoints":"xs"},` to
`{"caption":"Vice county","field":"#higher_geography:Vice County:name#","hide-breakpoints":"xs,sm,md"},`
