### ISSUE TITLE
Non-staff users can access all data by creating their own activity

### ISSUE THREAD

**Issue by simonrolph** [Sheffield-Rotherham-Wildlife-Trust/NatureCounts#59]
a. is this an issue?

Solution: Limit activity creation to staff only?

Make /activities/edit as staff role only
remove: <a href="/activities/edit" class="btn btn-primary">Create new activity</a> from activities
then add a link in the menu to /activities/edit

**Comment by johnvanbreda** [comment]
@simonrolph an alternative is to change the Group Data Inclusion option (on the Edit tab of the activity edit page) so that only records posted explicitly to the activity are allowed. Then activities can't be used to sweep up other records into a report.

**Comment by simonrolph** [comment]
And  I realised that by making the edit activity page as staff only then non-staff users wouldn't be able to manage users in their activity.

That alternative would work, but we'd lose nice bioblitz features of pulling in all records

It's not really urgent because the explore activity pages don't have a download button so I'll leave it as is for the moment. And anyway I'm hesitant to change things until I've come up with the best way to do it now that I've got 6 nature Counts sites to manage.........

**Comment by simonrolph** [comment]
Proposed solution:

Only staff role users can create activities

Staff role users can edit activities as before (full access to all options) but they will have to do it via a different page listing the activities.

Activity admins, if they are not staff users can access restricted page which allows editing of:

- Group name
- Group description
- Group type
- Logo
- Users management Group administrators and other group members

**Comment by johnvanbreda** [comment]
See https://record.wildsheffield.com/activities/staff.
I've updated the existing activities list page to remove the Create button. Also the edit page no longer has a filter. It still allows you to set the group type, how users join the group, how to decide which records to include, simply because the page doesn't have configuration for removing these at the moment. Shall I hide these with CSS, or do you think it is worth the effort to update the configuration options so the controls can be completely excluded from the non-staff edit page @simonrolph?

**Comment by simonrolph** [comment]
Hiding it with CSS is fine by me, thanks.

**Comment by johnvanbreda** [comment]
Done - see file /public_html/sites/default/files/indicia/css/node.49.css.
